title: The New Dynamic
baseURL: https://www.thenewdynamic.com
DefaultContentLanguage: en

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  tnd_redirects:
    use_aliases: true

social:
  twitter: theNewDynamic

outputs:
  home:
    - HTML
    - netlify_redir

module:
  imports:
    - path: github.com/theNewDynamic/hugo-component-tnd-forms
    - path: github.com/theNewDynamic/hugo-module-tnd-socials
    - path: github.com/theNewDynamic/hugo-module-tnd-redirects
    - path: github.com/theNewDynamic/hugo-module-tnd-styleguide
    - path: github.com/theNewDynamic/hugo-module-tnd-netlify-cms
