title: The New Dynamic
baseURL: https://www.thenewdynamic.com
DefaultContentLanguage: en

params:
  tnd_redirects:
    use_aliases: true

social:
  twitter: theNewDynamic

build:
  writeStats: true

outputs:
  home:
    - HTML
    - netlify_redir

module:
  imports:
    - path: github.com/theNewDynamic/hugo-component-tnd-forms
      imports:
        - source: layouts
          target: layouts
    - path: github.com/theNewDynamic/hugo-module-tnd-socials
    - path: github.com/theNewDynamic/hugo-module-tnd-redirects

