DefaultContentLanguage: en

social:
  twitter: theNewDynamic

module:
  imports:
    - path: github.com/theNewDynamic/hugo-component-tnd-forms
      imports:
        - source: layouts
          target: layouts
    - path: github.com/theNewDynamic/hugo-module-socials

