title: The New Dynamic
baseURL: https://www.thenewdynamic.com
DefaultContentLanguage: en

markup:
  highlight:
    style: monokai
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

social:
  twitter: theNewDynamic
outputs:
  home:
    - HTML

privacy:
  youtube:
    privacyEnhanced: true
  twitter:
    enableDNT: true
