title: The New Dynamic
baseURL: https://www.thenewdynamic.com
DefaultContentLanguage: en

markup:
  highlight:
    style: monokai
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

social:
  twitter: theNewDynamic
outputs:
  home:
    - HTML
    - tnd_redirects_netlify

module:
  imports:
    - path: github.com/theNewDynamic/hugo-component-tnd-forms
    - path: github.com/theNewDynamic/hugo-module-tnd-socials
    - path: github.com/theNewDynamic/hugo-module-tnd-redirects
    - path: github.com/theNewDynamic/hugo-module-tnd-netlifycms
    - path: github.com/theNewDynamic/hugo-component-tnd-blocks
    - path: github.com/theNewDynamic/hugo-module-tnd-styleguide
    - path: github.com/theNewDynamic/hugo-module-tnd-icons
    - path: github.com/theNewDynamic/hugo-module-tnd-func
    - path: github.com/theNewDynamic/hugo-module-tnd-tags
    #- path: github.com/theNewDynamic/hugo-module-tnd-seo
    - path: github.com/theNewDynamic/hugo-component-tnd-seo
    - path: github.com/theNewDynamic/hugo-workshop-starter
      mounts:
        source: content/products
        target: content/products
        lang: en
