tnd_forms:
  css:
    submit: block text-xl text-white bg-gray-800 hover:bg-gradient w-full px-4 py-2 rounded lowercase
tnd_redirects:
  use_aliases: true
tnd_socials:
  services:
    - name: github
      handle: theNewDynamic
      icon: github
    - name: twitter
      handle: theNewDynamic
tnd_iubenda:
  no_markup: false
  version: 'v1.1'
tnd_headers:
  groups:
    - headers:
      - key: Content-Security-Policy
        value: 
        - default-src 'self';
        - script-src 'self' 'unsafe-eval' https://cdn.usefathom.com https://identity.netlify.com https://unpkg.com;
        - style-src 'self' 'unsafe-inline';
        - prefetch-src https://thenewdynamic.imgix.net;
        - object-src 'none';
        - img-src 'self' https://thenewdynamic.imgix.net https://img3.usefathom.com;
        - font-src 'self';
        - base-uri 'none';
        - connect-src 'self' https://cdn.usefathom.com;
      - key: Strict-Transport-Security
        value: max-age=15768000
      - key: X-Xss-Protection
        value: 1; mode=block
      - key: X-Frame-Options
        value: DENY
      - key: X-Content-Type-Options
        value: nosniff
      - key: Referrer-Policy
        value: strict-origin-when-cross-origin
      - key: Feature-Policy
        value: camera 'none'; geolocation 'none'; microphone 'none'
addresses:
  - 234 Fifth Ave. • New York, NY • 10001
  - 4267 St Laurent Blvd, Montréal, Québec H2W 1Z4
