theme = "the-new-dynamic-hugo-base"
DefaultContentLanguage = "en"
languageCode = "en-us"
baseurl = "/"


author = "Bud Parr"
copyright = "Copyright (c) 2008 - 2014, Bud Parr; all rights reserved."
canonifyurls = true
paginate = 3

title = "the New Dynamic"
weight = 1

[params]

  hero_copy = "A dedicated web team for mission-driven organizations. "
