[build]
publish = "public"
command = "hugo --gc --minify"
#functions = "static/.functions"

[context.production.environment]
HUGO_VERSION = "0.50"
HUGO_ENV = "production"
#HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.50"

[context.branch-deploy.environment]
HUGO_VERSION = "0.50"

[context.branch-deploy]
#command = "yarn start"
command = "hugo --gc --minify -b $DEPLOY_URL"