[build]
publish = "public"
command = "hugo --minify -e netlify"

[dev]
  framework = "hugo" # or "#static" to force a static server
  command = "npm run start"

[context]

[context.production]

    [context.production.environment]
    HUGO_VERSION = "0.73.0"
    HUGO_ENV = "production"
    GO_VERSION = "1.14"
    NODE_VERSION="10.13.0"

    [context.deploy-preview.environment]
    HUGO_VERSION = "0.73.0"

[context.deploy-preview]
command = "hugo --minify -e netlify -D -b $DEPLOY_PRIME_URL"


[context.branch-deploy]
command = "hugo --minify -e netlify -b $DEPLOY_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.73.0"

  [context.master]
  command = "hugo --minify -e netlify -b $DEPLOY_URL"

    [context.master.environment]
    HUGO_VERSION = "0.73.0"
[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'self';script-src 'self' 'unsafe-eval' https://cdn.usefathom.com/ https://identity.netlify.com https://unpkg.com;style-src 'self' 'unsafe-inline';prefetch-src https://thenewdynamic.imgix.net;object-src 'none';img-src 'self' https://thenewdynamic.imgix.net;font-src 'self';base-uri 'none';connect-src https://cdn.usefathom.com/;"
Strict-Transport-Security = "max-age=15768000"
X-Xss-Protection = "1; mode=block"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"


# require-trusted-types-for 'script';report-uri //thenewdynamic.com/csp