title: TND Styleguide
baseURL: https://styleguide.thenewdynamic.com
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
